"""
Django LOCAL settings for project_greenhouse project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from .settings import *

DEBUG = True

SECRET_KEY = ''

ALLOWED_HOSTS += []

VAGRANTAPI_URL = "https://app.vagrantup.com/api/v1/"
VAGRANTAPI_KEY = ""


SHELL_PLUS = "ipython"

LOGGING['handlers']['splunk']['token'] = os.getenv('SPLUNK_TOKEN', '')
LOGGING['handlers']['splunk']['host'] = os.getenv('SPLUNK_HOST', '')
LOGGING['handlers']['splunk']['port'] = int(os.getenv('SPLUNK_PORT', ''))

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': '',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
    }
}
"""

MAX_POOL = 10
MEMORY_FREELIMIT = 1024 * 1024 * 1024  # 1024MB
RUN_MINUTES = 70
SLEEP_SECONDS = 60