Vagrant.configure("2") do |config|
  config.vm.box = "{{ username }}/{{ boxname }}"
  #config.vm.box_version = "0.0.1"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.hostname = "{{ username }}-{{ boxname }}"
  config.disksize.size = '8GB'
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |vb, override|
         vb.name = "{{ username }}-{{ boxname }}"
         vb.customize ["modifyvm", :id, "--memory", 512]
         vb.customize ["modifyvm", :id, "--cpus", 1]
  end
end
